name: Build and Publish image to Docker Hub
on:
  push:
    branches:
      - main
    paths:
      - 'api/Dockerfile'
      - 'front-end-nextjs/Dockerfile'

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: build image
        run: |
          docker build ./api/ -t 1213117686/devops-qr-code-backend:latest
          docker build ./front-end-nextjs/ -t 1213117686/devops-qr-code-frontend:latest

      - name: login to docker hub
        run: |
          echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u 1213117686 --password-stdin

      - name: push images
        run: |
          docker push 1213117686/devops-qr-code-backend:latest
          docker push 1213117686/devops-qr-code-frontend:latest
